server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
vaadin.launch-browser=true
logging.level.org.springframework.security=INFO

spring.devtools.restart.enabled=false


# spring-boot-starter-mail properties
spring.mail.host=s208.goserver.host
spring.mail.port=465
spring.mail.protocol=smtp
spring.mail.username=XXX
spring.mail.password=XXX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.transport.protocol=smtp


#Nur während der Entwicklung, erspart neue Anmeldung nach rebuild der Anwendung:
server.servlet.session.persistent=true  

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss} %clr(%logger{0}) %highlight(%level): %msg%n

# HikariCP configuration
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.pool-name=MyHikariCP
#logging.level.com.zaxxer.hikari=DEBUG

app.aes.secret=${APP_AES_SECRET}