server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
vaadin.launch-browser=true
logging.level.org.springframework.security=INFO

spring.devtools.restart.enabled=false


# spring-boot-starter-mail properties
spring.mail.host=s208.goserver.host
spring.mail.port=465
spring.mail.protocol=smtp
spring.mail.username=XXX
spring.mail.password=XXX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.transport.protocol=smtp